### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by aamershahzad2** [Ingenico-ePayments/connect-sdk-client-swift-example#1]
App crash after payment has been successfully processed.

**Comment by LeonStemerdink** [comment]
The crash is probably caused by [this issue](https://github.com/Ingenico-ePayments/connect-sdk-client-swift/issues/3) on the sdk, which should be resolved shortly.

**Comment by LeonStemerdink** [comment]
The issue I referenced in my previous comment has been fixed with [release 3.2.0 of the Ingenico Connect Swift Client SDK](https://github.com/Ingenico-ePayments/connect-sdk-client-swift/releases/tag/3.2.0). Can you verify that using this version of the SDK no longer causes the App to crash?
